<?php

$lang = [
    'langSelect' => 'Idiomas',
    'title' => 'Painel Administrativo',

    'menu_top' => [
        'home' => 'Início',
        'news' => 'Notícias',
        'exit' => 'Sair',
    ],

    'menu_left' => [
        '_home' => 'Início',
        'home' => 'Estatísticas',
        'users' => 'Ver Usuários',
        'sender' => 'Campanhas de Email',
        'settings' => 'Configurações',
        'adminpass' => 'Acesso Admin',

        '_transactions' => 'Transações',
        'purchases' => 'Histórico de Compras',
        'exchanges' => 'Histórico de Trocas',
        'deposits' => 'Histórico de Depósitos',
        'sales' => 'Histórico de Vendas',
        'withdraws' => 'Histórico de Saques',

        '_sections' => 'Seções',
        'news' => 'Notícias',
        'about' => 'Sobre',
        'rules' => 'Regras',
        'contact' => 'Contato',

        'login' => 'Entrar',
    ],

    'error_messages' => [
        'accountBanned' => 'Esta conta foi banida',
        'wrongLogin' => 'Email e/ou senha incorretos',
        'notfoundAccount' => 'O email especificado não está cadastrado',
        'usernameInUse' => 'O usuário informado já está em uso',
        'passwordMatch' => 'As senhas não combinam',
        'emptyPassword' => 'Senha incorreta ou não informada',
        'emptyLogin' => 'Usuário incorreto ou não informado',
        'emailInvalid' => 'O email informado não parece válido',
        'invalidData' => 'Houve erros com os dados que você forneceu',
        'requestReset' => 'Your email or IP has already been sent a password in the last 15 minutes',
        'oldpassword' => 'Senha antiga incorreta!',
        'noresults' => 'Nenhum resultado para exibir',
        'itemNotFound' => 'Item não encontrado com o ID especificado',
    ],

    'success_messages' => [
        'changesSaved' => 'Alterações salvas com sucesso!',
        'deleted' => 'Item deletado com sucesso!',
        'created' => 'Item criado com sucesso!',
        'cleaned' => 'Dados limpados com sucesso!',
    ],

    'btn' => [
        'send' => 'Enviar',
        'edit' => 'Editar',
        'delete' => 'Deletar',
        'create' => 'Criar',
        'cancel' => 'Cancelar',
        'login' => 'Entrar',
        'register' => 'Registrar',
        'forgotL' => 'Resetar Senha',
        'forgot' => 'Enviar Link de Reset',
        'save' => 'Salvar',
        'clear' => 'Limpar',
        'search' => 'Buscar',
        'ban' => 'Banir',
        'unban' => 'Desbanir',
    ],

    'common' => [
        'email' => 'Email',
        'password' => 'Senha',
        'auth' => 'Autorização',
        'password_old' => 'Senha Antiga',
        'password_new' => 'Nova Senha',
        'users' => 'Usuários',
        'days' => 'Dias',
        'username' => 'Usuário',
        'copyright' => 'Todos os direitos reservados.',
        'referrer' => 'Indicado por',
        'p_balance' => 'Saldo de Compras',
        'w_balance' => 'Saldo de Saque',
        'ref_earnings' => 'Ganhos de Referidos',
        'paid' => 'Total Pago',
        'resgetedOn' => 'Cadastrado Em',
        'deposits' => 'Depósitos',
        'withdraws' => 'Saques',
        'referrals' => 'Referidos',
        'date' => 'Data',
        'qtd' => 'Quantidade',
        'count' => 'Contagem',
        'wallet' => 'Carteira',
        'amount' => 'Valor',
        'name' => 'Nome',
        'title' => 'Título',
        'content' => 'Conteúdo',
        'actions' => 'Ações',
        'status' => 'Status',
        'sold' => 'Vendido',
        'gived' => 'Dado',
        'received' => 'Recebido',
        'itemName' => 'Item',
        'price' => 'Preço',
        'min' => 'Min.',
        'cost' => 'Custo',
        'yes' => 'Sim',
        'no' => 'Não',
        'total' => 'Total',
        'perHour' => 'Por Hora',
        'totalCollected' => 'Total Coletado',
        'confirmdelete' => 'Tem certeza que deseja apagar este item? Esta ação não pode ser desfeita.',
    ],

    'login' => [
        'title' => 'Entrar',
        'requestSended' => 'Link de reset enviado para seu email',
        'resetSuccess' => 'Sua senha foi alterada com sucesso, agora você já pode acessar sua conta.',
    ],

    'recovery' => [
        'title' => 'Recuperar Senha',
        'requestSended' => 'Link de reset enviado para seu email',
        'resetSuccess' => 'Sua senha foi alterada com sucesso, agora você já pode acessar sua conta.',
    ],

    'settings' => [
        'title' => 'Configurações',
        '_conversions' => 'Conversões',
        '_productions' => 'Produções',
        '_itemprices' => 'Preços dos Itens',
        '_general' => 'Geral',
        'min_payout' => 'Saque Mínimo',
        'swapBonus' => 'Bonus de Troca(%)',
        'sellPercent' => '% de Saldo de Saque nas Vendas',
        'adminLang' => 'Idioma da Administração',
        'error_paymentMin' => 'O valor mínimo de pagamento não pode ser inferior a 0',
        'error_percentExt' => 'A porcentagem a ser trocada deve ser de 1 a 99',
        'error_percentOut' => '% de moedas na saída na venda deve ser de 1 a 99',
        'error_minfruits' => 'Quantos itens = 1 moeda, deve ser de 1 a 50.000',
        'error_productionMin' => 'Ajuste incorreto do rendimento do item por hora! Mínimo 6',
        'error_itemprice' => 'O valor mínimo de um item não deve ser inferior a 1 moeda',
    ],

    'adminpass' => [
        'title' => 'Acesso a Administração',
        'username' => 'Alterar Usuário Admin',
        'password' => 'Nova Senha do Admin',
        'password_confirmation' => 'Confirme a Nova Senha',
        'password_old' => 'Senha Atual',
        'error_emptyfields' => 'Você deixou campos obrigatórios vazios!',
        'error_oldpass' => 'Senha atual incorreta!',
        'error_newpassmatch' => 'As senhas não combinam!',
    ],

    'about' => [
        'title' => 'Sobre o Projeto',
        'content' => 'Conteúdo da Página',
    ],

    'rules' => [
        'title' => 'Regras do Projeto',
        'content' => 'Conteúdo da Página',
    ],

    'contacts' => [
        'title' => 'Página de Contato',
        'content' => 'Conteúdo da Página',
    ],

    'news' => [
        'title' => 'Notícias',
        'list' => 'Listar Notícias',
        'titleError' => 'O título não pode ter menos de 3 caracteres',
    ],

    'payouts' => [
        'title' => 'Histórico de Saques',
        '_paid' => 'Pago',
        '_balance' => 'Saldo na Payeer',
        '_daily' => 'Diariamente',
        '_month' => 'Últimos 30 dias',
        'payments' => 'Pagamentos',
        'legend_graph1' => 'Histórico de Depósitos (Quantidade)',
        'footer_graph1' => 'Últimos 30 dias',
        'legend_graph2' => 'Histórico de Depósitos (Quantidade)',
        'footer_graph2' => 'Últimos 30 dias',
        'legend_graph3' => 'Histórico de Depósitos (Quantidade)',
        'footer_graph3' => 'Últimos 30 dias',
    ],

    'story_insert' => [
        'title' => 'Histórico de Depósitos',
        '_list' => 'Depósitos',
        '_daily' => 'Diariamente',
        '_month' => 'Últimos 30 dias',
        'deposits' => 'Depósitos',
        'legend_graph1' => 'Histórico de Depósitos (Quantidade)',
        'footer_graph1' => 'Últimos 30 dias',
        'legend_graph2' => 'Histórico de Depósitos (Quantidade)',
        'footer_graph2' => 'Últimos 30 dias',
        'legend_graph3' => 'Histórico de Depósitos (Quantidade)',
        'footer_graph3' => 'Últimos 30 dias',
    ],

    'story_sell' => [
        'title' => 'Venda de Moedas',
    ],

    'story_swap' => [
        'title' => 'Histórico de Trocas',
    ],

    'story_buy' => [
        'title' => 'Histórico de Compras',
    ],

    'sendermail' => [
        'title' => 'Boletim Informativo',
        'list' => 'Lista de Boletins',
        'add' => 'Novo Boletim',
        'sended' => 'Enviado',
        'status_send' => 'Enviando',
        'status_ok' => 'Completo',
        'markers' => 'Marcadores para Substituição',
        'created' => 'Boletim informativo está na fila para execução',
        'error_minContent' => 'A mensagem deve ter mais de 10 caracteres',
        'error_minTitle' => 'O título deve ter mais de 3 caracteres',
    ],

    'users' => [
        'title' => 'Gerenciar Usuários',
        'ref_earns' => 'Ganhos de Referidos',
        'ref_pays' => 'Brought a referrer',
        'lastLogin' => 'Último Login',
        'lastIP' => 'Último IP',
        'bannedStatus' => 'Banido',
        'addTo' => 'Adicionar Saldo',
        'removeFrom' => 'Deduzir Saldo',
        'itemAdded' => 'Item adicionado com sucesso!',
        'balanceMinus' => 'Deduzido %s do saldo do usuário!',
        'balancePlus' => 'Adicionado %s ao saldo do usuário!',
        'banned' => 'Usuário banido com sucesso!',
        'unbanned' => 'Usuário desbanido com sucesso!',
    ],

    'dashboard' => [
        'title' => 'Estatísticas Gerais',
        'total_users' => 'Usuários Cadastrados',
        'bought' => 'Comprado',
        'warehouses' => 'Nos Armazéns',
        'collected' => 'Total Coletado',
        'profit' => 'Lucro Total',
    ],
];